// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Solisystems.Data;

#nullable disable

namespace Solisystems.Migrations
{
    [DbContext(typeof(DbContextClass))]
    partial class DbContextClassModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Solisystems.Domain.Entities.Category", b =>
                {
                    b.Property<string>("CategoryCode")
                        .HasColumnType("text");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CategoryCode");

                    b.HasIndex("CategoryCode")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryCode = "1",
                            CategoryName = "Pain Relief",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4204)
                        },
                        new
                        {
                            CategoryCode = "3",
                            CategoryName = "Digestive Health",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4227)
                        },
                        new
                        {
                            CategoryCode = "5",
                            CategoryName = "Baby Care",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4233)
                        },
                        new
                        {
                            CategoryCode = "7",
                            CategoryName = "Cold & Allergy",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4264)
                        },
                        new
                        {
                            CategoryCode = "9",
                            CategoryName = "Deodorants",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4274)
                        },
                        new
                        {
                            CategoryCode = "11",
                            CategoryName = "Diabetes Management",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4282)
                        },
                        new
                        {
                            CategoryCode = "13",
                            CategoryName = "Weight Management & Nutritional Foods",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4288)
                        },
                        new
                        {
                            CategoryCode = "14",
                            CategoryName = "Physical Fitness & Exercise Equipment",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4296)
                        },
                        new
                        {
                            CategoryCode = "15",
                            CategoryName = "Health Supports",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4304)
                        },
                        new
                        {
                            CategoryCode = "16",
                            CategoryName = "Compression Support",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4311)
                        },
                        new
                        {
                            CategoryCode = "17",
                            CategoryName = "Multi-Cultural Beauty Care",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4316)
                        },
                        new
                        {
                            CategoryCode = "19",
                            CategoryName = "Eye & Ear Care",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4322)
                        },
                        new
                        {
                            CategoryCode = "21",
                            CategoryName = "Family Planning",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4327)
                        },
                        new
                        {
                            CategoryCode = "23",
                            CategoryName = "Feminine Care",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4332)
                        },
                        new
                        {
                            CategoryCode = "25",
                            CategoryName = "First Aid",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4337)
                        },
                        new
                        {
                            CategoryCode = "27",
                            CategoryName = "Foot Care",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4341)
                        },
                        new
                        {
                            CategoryCode = "29",
                            CategoryName = "Hair Care",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4345)
                        },
                        new
                        {
                            CategoryCode = "30",
                            CategoryName = "Homeopathic Kits & Single Remedies",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4372)
                        },
                        new
                        {
                            CategoryCode = "31",
                            CategoryName = "Alternative Therapy",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4380)
                        },
                        new
                        {
                            CategoryCode = "33",
                            CategoryName = "Shaving & Grooming",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4386)
                        },
                        new
                        {
                            CategoryCode = "35",
                            CategoryName = "Oral Care",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4391)
                        },
                        new
                        {
                            CategoryCode = "37",
                            CategoryName = "Skin Care",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4396)
                        },
                        new
                        {
                            CategoryCode = "38",
                            CategoryName = "Nicotine Replacement Therapy",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4404)
                        },
                        new
                        {
                            CategoryCode = "39",
                            CategoryName = "Sun Care",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4408)
                        },
                        new
                        {
                            CategoryCode = "40",
                            CategoryName = "Trial & Travel Sizes",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4414)
                        },
                        new
                        {
                            CategoryCode = "41",
                            CategoryName = "Vitamins & Dietary Supplements",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4419)
                        },
                        new
                        {
                            CategoryCode = "43",
                            CategoryName = "Wets & Drys",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4424)
                        },
                        new
                        {
                            CategoryCode = "44",
                            CategoryName = "Batteries",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4429)
                        },
                        new
                        {
                            CategoryCode = "51",
                            CategoryName = "Automotive Supplies",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4434)
                        },
                        new
                        {
                            CategoryCode = "53",
                            CategoryName = "Confections",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4439)
                        },
                        new
                        {
                            CategoryCode = "54",
                            CategoryName = "Cosmetics",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4466)
                        },
                        new
                        {
                            CategoryCode = "55",
                            CategoryName = "Electronics & Audio/Video",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4471)
                        },
                        new
                        {
                            CategoryCode = "56",
                            CategoryName = "Food & Beverages",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4476)
                        },
                        new
                        {
                            CategoryCode = "57",
                            CategoryName = "Gifts & Novelties",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4483)
                        },
                        new
                        {
                            CategoryCode = "58",
                            CategoryName = "Greeting Cards & Other Assoc. Mfg. Items",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4488)
                        },
                        new
                        {
                            CategoryCode = "59",
                            CategoryName = "Hair Accessories",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4494)
                        },
                        new
                        {
                            CategoryCode = "60",
                            CategoryName = "Household Products",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4499)
                        },
                        new
                        {
                            CategoryCode = "61",
                            CategoryName = "Leather/Vinyl Goods",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4506)
                        },
                        new
                        {
                            CategoryCode = "62",
                            CategoryName = "Magazines & Books",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4514)
                        },
                        new
                        {
                            CategoryCode = "64",
                            CategoryName = "Pet & Animal Supplies",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4519)
                        },
                        new
                        {
                            CategoryCode = "65",
                            CategoryName = "Photography",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4546)
                        },
                        new
                        {
                            CategoryCode = "66",
                            CategoryName = "Seasonal Products",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4553)
                        },
                        new
                        {
                            CategoryCode = "67",
                            CategoryName = "Sewing & Crafts",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4558)
                        },
                        new
                        {
                            CategoryCode = "68",
                            CategoryName = "Soft Lines",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4562)
                        },
                        new
                        {
                            CategoryCode = "69",
                            CategoryName = "Sports & Recreation",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4568)
                        },
                        new
                        {
                            CategoryCode = "70",
                            CategoryName = "School & Office",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4573)
                        },
                        new
                        {
                            CategoryCode = "71",
                            CategoryName = "Tobacco",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4578)
                        },
                        new
                        {
                            CategoryCode = "72",
                            CategoryName = "Toys",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4583)
                        },
                        new
                        {
                            CategoryCode = "73",
                            CategoryName = "Fragrances",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4588)
                        },
                        new
                        {
                            CategoryCode = "78",
                            CategoryName = "Professional OTCs In Pharmacy",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4593)
                        },
                        new
                        {
                            CategoryCode = "90",
                            CategoryName = "Home Health Care",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4598)
                        },
                        new
                        {
                            CategoryCode = "94",
                            CategoryName = "Incontinence",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4607)
                        },
                        new
                        {
                            CategoryCode = "95",
                            CategoryName = "Patient Skin Care",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4612)
                        },
                        new
                        {
                            CategoryCode = "96",
                            CategoryName = "Home Diag &Patient Aids For Daily Living",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4637)
                        });
                });

            modelBuilder.Entity("Solisystems.Domain.Entities.ProductEntity", b =>
                {
                    b.Property<string>("ProductCode")
                        .HasColumnType("text");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductCode");

                    b.HasIndex("CategoryCode");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductCode = "0000000001",
                            CategoryCode = "1",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4654),
                            ProductName = "Product 01"
                        },
                        new
                        {
                            ProductCode = "0000000002",
                            CategoryCode = "1",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4666),
                            ProductName = "Product 02"
                        },
                        new
                        {
                            ProductCode = "0000000003",
                            CategoryCode = "1",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4672),
                            ProductName = "Product 03"
                        },
                        new
                        {
                            ProductCode = "0000000004",
                            CategoryCode = "9",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4677),
                            ProductName = "Product 04"
                        },
                        new
                        {
                            ProductCode = "0000000005",
                            CategoryCode = "9",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4683),
                            ProductName = "Product 05"
                        },
                        new
                        {
                            ProductCode = "0000000006",
                            CategoryCode = "9",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4689),
                            ProductName = "Product 06"
                        },
                        new
                        {
                            ProductCode = "0000000007",
                            CategoryCode = "9",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4694),
                            ProductName = "Product 07"
                        },
                        new
                        {
                            ProductCode = "0000000008",
                            CategoryCode = "17",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4700),
                            ProductName = "Product 08"
                        },
                        new
                        {
                            ProductCode = "0000000009",
                            CategoryCode = "17",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4704),
                            ProductName = "Product 09"
                        },
                        new
                        {
                            ProductCode = "0000000010",
                            CategoryCode = "17",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4711),
                            ProductName = "Product 10"
                        },
                        new
                        {
                            ProductCode = "0000000011",
                            CategoryCode = "17",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4716),
                            ProductName = "Product 11"
                        },
                        new
                        {
                            ProductCode = "0000000012",
                            CategoryCode = "21",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4721),
                            ProductName = "Product 12"
                        },
                        new
                        {
                            ProductCode = "0000000013",
                            CategoryCode = "21",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4726),
                            ProductName = "Product 13"
                        },
                        new
                        {
                            ProductCode = "0000000014",
                            CategoryCode = "21",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4731),
                            ProductName = "Product 14"
                        },
                        new
                        {
                            ProductCode = "0000000015",
                            CategoryCode = "21",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4758),
                            ProductName = "Product 15"
                        },
                        new
                        {
                            ProductCode = "0000000016",
                            CategoryCode = "30",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4763),
                            ProductName = "Product 16"
                        },
                        new
                        {
                            ProductCode = "0000000017",
                            CategoryCode = "30",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4768),
                            ProductName = "Product 17"
                        },
                        new
                        {
                            ProductCode = "0000000018",
                            CategoryCode = "30",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4775),
                            ProductName = "Product 18"
                        },
                        new
                        {
                            ProductCode = "0000000019",
                            CategoryCode = "30",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4781),
                            ProductName = "Product 19"
                        },
                        new
                        {
                            ProductCode = "0000000020",
                            CategoryCode = "38",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4785),
                            ProductName = "Product 20"
                        },
                        new
                        {
                            ProductCode = "0000000021",
                            CategoryCode = "38",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4790),
                            ProductName = "Product 21"
                        },
                        new
                        {
                            ProductCode = "0000000022",
                            CategoryCode = "38",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4795),
                            ProductName = "Product 22"
                        },
                        new
                        {
                            ProductCode = "0000000023",
                            CategoryCode = "38",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4802),
                            ProductName = "Product 23"
                        },
                        new
                        {
                            ProductCode = "0000000024",
                            CategoryCode = "38",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4807),
                            ProductName = "Product 24"
                        },
                        new
                        {
                            ProductCode = "0000000025",
                            CategoryCode = "40",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4812),
                            ProductName = "Product 25"
                        },
                        new
                        {
                            ProductCode = "0000000026",
                            CategoryCode = "40",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4817),
                            ProductName = "Product 26"
                        },
                        new
                        {
                            ProductCode = "0000000027",
                            CategoryCode = "40",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4823),
                            ProductName = "Product 27"
                        },
                        new
                        {
                            ProductCode = "0000000028",
                            CategoryCode = "40",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4827),
                            ProductName = "Product 28"
                        },
                        new
                        {
                            ProductCode = "0000000029",
                            CategoryCode = "55",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4860),
                            ProductName = "Product 29"
                        },
                        new
                        {
                            ProductCode = "0000000030",
                            CategoryCode = "55",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4865),
                            ProductName = "Product 30"
                        },
                        new
                        {
                            ProductCode = "0000000031",
                            CategoryCode = "55",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4870),
                            ProductName = "Product 31"
                        },
                        new
                        {
                            ProductCode = "0000000032",
                            CategoryCode = "55",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4875),
                            ProductName = "Product 32"
                        },
                        new
                        {
                            ProductCode = "0000000033",
                            CategoryCode = "55",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4880),
                            ProductName = "Product 33"
                        },
                        new
                        {
                            ProductCode = "0000000034",
                            CategoryCode = "60",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4887),
                            ProductName = "Product 34"
                        },
                        new
                        {
                            ProductCode = "0000000035",
                            CategoryCode = "60",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4892),
                            ProductName = "Product 35"
                        },
                        new
                        {
                            ProductCode = "0000000036",
                            CategoryCode = "60",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4897),
                            ProductName = "Product 36"
                        },
                        new
                        {
                            ProductCode = "0000000037",
                            CategoryCode = "60",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4929),
                            ProductName = "Product 37"
                        },
                        new
                        {
                            ProductCode = "0000000038",
                            CategoryCode = "65",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4936),
                            ProductName = "Product 38"
                        },
                        new
                        {
                            ProductCode = "0000000039",
                            CategoryCode = "65",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4941),
                            ProductName = "Product 39"
                        },
                        new
                        {
                            ProductCode = "0000000040",
                            CategoryCode = "65",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4946),
                            ProductName = "Product 40"
                        },
                        new
                        {
                            ProductCode = "0000000041",
                            CategoryCode = "65",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4951),
                            ProductName = "Product 41"
                        },
                        new
                        {
                            ProductCode = "0000000042",
                            CategoryCode = "66",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4956),
                            ProductName = "Product 42"
                        },
                        new
                        {
                            ProductCode = "0000000043",
                            CategoryCode = "67",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4961),
                            ProductName = "Product 43"
                        },
                        new
                        {
                            ProductCode = "0000000044",
                            CategoryCode = "68",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4977),
                            ProductName = "Product 44"
                        },
                        new
                        {
                            ProductCode = "0000000045",
                            CategoryCode = "70",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4982),
                            ProductName = "Product 45"
                        },
                        new
                        {
                            ProductCode = "0000000046",
                            CategoryCode = "71",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4988),
                            ProductName = "Product 46"
                        },
                        new
                        {
                            ProductCode = "0000000047",
                            CategoryCode = "72",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4992),
                            ProductName = "Product 47"
                        },
                        new
                        {
                            ProductCode = "0000000048",
                            CategoryCode = "73",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(4997),
                            ProductName = "Product 48"
                        },
                        new
                        {
                            ProductCode = "0000000049",
                            CategoryCode = "90",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(5002),
                            ProductName = "Product 49"
                        },
                        new
                        {
                            ProductCode = "0000000050",
                            CategoryCode = "90",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(5007),
                            ProductName = "Product 50"
                        },
                        new
                        {
                            ProductCode = "0000000051",
                            CategoryCode = "90",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(5032),
                            ProductName = "Product 51"
                        },
                        new
                        {
                            ProductCode = "0000000052",
                            CategoryCode = "90",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(5037),
                            ProductName = "Product 52"
                        },
                        new
                        {
                            ProductCode = "0000000053",
                            CategoryCode = "95",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(5042),
                            ProductName = "Product 53"
                        },
                        new
                        {
                            ProductCode = "0000000054",
                            CategoryCode = "95",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(5046),
                            ProductName = "Product 54"
                        },
                        new
                        {
                            ProductCode = "0000000055",
                            CategoryCode = "95",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(5051),
                            ProductName = "Product 55"
                        },
                        new
                        {
                            ProductCode = "0000000056",
                            CategoryCode = "95",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(5056),
                            ProductName = "Product 56"
                        },
                        new
                        {
                            ProductCode = "0000000057",
                            CategoryCode = "95",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(5060),
                            ProductName = "Product 57"
                        },
                        new
                        {
                            ProductCode = "0000000058",
                            CategoryCode = "95",
                            CreationDate = new DateTime(2023, 8, 13, 6, 0, 56, 288, DateTimeKind.Utc).AddTicks(5065),
                            ProductName = "Product 58"
                        });
                });

            modelBuilder.Entity("Solisystems.Domain.Entities.ProductEntity", b =>
                {
                    b.HasOne("Solisystems.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Solisystems.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
